version: "3.9"

services:
    database:
        image: postgres
        container_name: database
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=usr_rentx
            - POSTGRES_PASSWORD=usr_rentx
            - POSTGRES_DB=rentalx
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: rentx
        restart: always
        links:
            - database
        depends_on:
            - database
        ports:
            - 3333:3333
            - 9229:9229
        volumes:
            - .:/usr/app

volumes:
    pgdata:
        driver: local
